local map = Utils.map

map("n", "<leader>gs", function()
    require("neogit").open()
end)
map("n", "<leader><leader>gs", "<cmd>lua require('telescope.builtin').git_stash()<cr>")
map("n", "<leader>gd", "<cmd>DiffviewOpen<cr>")
map("n", "<leader>gh", "<cmd>lua require('telescope.builtin').git_commits()<cr>")
map("n", "<leader><leader>gh", "<cmd>lua require('telescope.builtin').git_bcommits()<cr>")
map("n", "<leader>gc", function()
    vim.cmd("DiffviewClose")
    local neogit = require("neogit")
    neogit.open()
    neogit.open({ "commit" })
    vim.fn.feedkeys("c")
end)
map("n", "<leader>gfx", "<cmd>Gitsigns reset_buffer<cr>")
map("n", "<leader>gfs", "<cmd>Gitsigns stage_buffer<cr>")
map("n", "<leader>gb", "<cmd>lua require('telescope.builtin').git_branches()<cr>")
map("n", "<leader><leader>gb", "<cmd>lua require('git_blame').run()<cr>")

map("n", "<leader>hj", "<cmd>Gitsigns next_hunk<cr>zz")
map("n", "<leader>hk", "<cmd>Gitsigns prev_hunk<cr>zz")
map("n", "<leader>hp", "<cmd>Gitsigns preview_hunk<cr>")
map({ "n", "v" }, "<leader>hs", "<cmd>Gitsigns stage_hunk<cr><ESC><cmd>DiffviewRefresh<cr>")
map("n", "<leader>hx", "<cmd>Gitsigns reset_hunk<cr><cmd>DiffviewRefresh<cr>")
map("n", "<leader>hu", "<cmd>Gitsigns undo_stage_hunk<cr><cmd>DiffviewRefresh<cr>")
